name = "HTTPStatus.jl"
uuid = "3343e0d9-c05a-4b80-a9dc-415350111698"
authors = ["Kracekumar <me@kracekumar.com>"]
version = "0.1.1"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

